---
title: Fashion Pria
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  vendor:
    title: Vendor
    output: true
name: Fashionpria.co.id
description: Konsultasi Vendor, Konveksi Produk Pria, Jasa Photo dan Jasa Iklan IG
  dan FB Online Shop Pria.
avatar: 
disqus: 
whatsapp: 6283890722797
google_analytics: 
url: http://www.fashionpria.co.id
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
